server:
  port: 8080

spring:
  application:
    name: blog-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ?????? my_blog_db ????????????
    url: jdbc:mysql://localhost:3306/my_blog_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "0525" # ????

# MyBatis ?? (?????? MyBatis-Plus????????????? MyBatis ?)
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.blog.entity
  configuration:
    map-underscore-to-camel-case: true # ??????????

# ????
logging:
  level:
    com.example.blog.mapper: debug # ?????? SQL ??