name: Deploy Frontend (Vue)

on:
  push:
    branches: [ main ]
    paths:
      - 'blog-frontend/**' # ğŸŸ¢ åªæœ‰æ”¹äº†å‰ç«¯æ–‡ä»¶æ‰è§¦å‘

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. æ„å»º Vue
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # ä¿æŒå’Œä½ æœ¬åœ°ä¸€è‡´

      - name: Build Frontend
        run: |
          cd blog-frontend
          npm install
          npm run build

      # 2. ä¼ è¾“é™æ€æ–‡ä»¶ (ç›´è¾¾ Nginx ç›®å½•)
      - name: Deploy to Nginx
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "blog-frontend/dist/*"
          target: "/home/flowblog/blog-frontend"
          strip_components: 2